CREATE TABLE YourLibrary.BALANCETAB ( 
	TRANSTYPE CHAR(1) CCSID 273 NOT NULL , 
	AMOUNT DECIMAL(15, 5) NOT NULL , 
	TRANSTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , 
	CONSTRAINT YourLibrary.Q_YourLibrary_BALANCETAB_TRANSTIME_00001 PRIMARY KEY( TRANSTIME ) )   
	  
	RCDFMT BAL        ; 