CREATE PROCEDURE YourLibrary.GETBALANCE ( 
	OUT BALANCE DECIMAL(15, 5) ) 
	DYNAMIC RESULT SETS 1 
	LANGUAGE SQL 
	SPECIFIC YourLibrary.GETBALANCE 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	SET OPTION  ALWBLK = *ALLREAD , 
	ALWCPYDTA = *OPTIMIZE , 
	COMMIT = *NONE , 
	DECRESULT = (31, 31, 00) , 
	DYNDFTCOL = *NO , 
	DYNUSRPRF = *USER , 
	SRTSEQ = *HEX   
	BEGIN 
  
  
SELECT 
( COALESCE ( ( SELECT SUM ( AMOUNT ) FROM YourLibrary.BALANCETAB WHERE TRANSTYPE = 'D' ) , 0 ) - 
COALESCE ( ( SELECT SUM ( AMOUNT ) FROM YourLibrary.BALANCETAB WHERE TRANSTYPE = 'W' ) , 0 ) ) 
INTO BALANCE 
FROM SYSIBM . SYSDUMMY1 ; 
  
END  ; 