CREATE PROCEDURE YourLibrary.PROCESSTRANSACTION ( 
	IN AMOUNT DECIMAL(15, 5) , 
	IN TTYPE CHAR(1) , 
	OUT BALANCE DECIMAL(15, 5) , 
	OUT MESSAGE CHAR(35) ) 
	LANGUAGE RPGLE 
	SPECIFIC YourLibrary.PROCESSTRANSACTION 
	NOT DETERMINISTIC 
	MODIFIES SQL DATA 
	CALLED ON NULL INPUT 
	EXTERNAL NAME 'YourLibrary/TRANSACT' 
	PARAMETER STYLE GENERAL ; 
  
GRANT ALTER , EXECUTE   
ON SPECIFIC PROCEDURE YourLibrary.PROCESSTRANSACTION 
TO YourUserName WITH GRANT OPTION ; 
  